import { defineConfig } from "tsup";

export default defineConfig([
  {
    entry: {
      index: "src/index.ts",
    },
    format: ["esm", "cjs"],
    dts: true,
    sourcemap: true,
    clean: true,
    splitting: false,
    treeshake: true,
    external: [
      "./backends/copilot.js",
      "./backends/claude.js",
      "./backends/vercel-ai.js",
      "./backends/mock-llm.js",
    ],
  },
  {
    entry: {
      "backends/copilot": "src/backends/copilot.ts",
      "backends/claude": "src/backends/claude.ts",
      "backends/vercel-ai": "src/backends/vercel-ai.ts",
      "backends/mock-llm": "src/backends/mock-llm.ts",
      "auth/index": "src/auth/index.ts",
      "chat/index": "src/chat/index.ts",
      "chat/core": "src/chat/core.ts",
      "chat/errors": "src/chat/errors.ts",
      "chat/events": "src/chat/events.ts",
      "chat/storage": "src/chat/storage.ts",
      "chat/sessions": "src/chat/sessions.ts",
      "chat/context": "src/chat/context.ts",
      "chat/accumulator": "src/chat/accumulator.ts",
      "chat/state": "src/chat/state.ts",
      "chat/backends": "src/chat/backends/index.ts",
      "chat/runtime": "src/chat/runtime.ts",
      "chat/react": "src/chat/react/index.ts",
      "chat/server": "src/chat/server/index.ts",
      "chat/sqlite": "src/chat/sqlite/index.ts",
      "testing": "src/testing/index.ts",
    },
    format: ["esm", "cjs"],
    dts: true,
    sourcemap: true,
    external: [
      "@github/copilot-sdk",
      "@anthropic-ai/claude-agent-sdk",
      "ai",
      "@ai-sdk/*",
      "zod",
      "react",
      "better-sqlite3",
      "node:crypto",
      "crypto",
    ],
    splitting: false,
    treeshake: true,
  },
]);
